import type { Platform } from "@/lib/platforms";
import { getArticle, type PlatformArticle } from "@/lib/platform-content";

export type QA = { q: string; a: string };
export type Benefit = { title: string; text: string };
export type Step = { title: string; text: string };
export type ComparisonRow = { feature: string; online: string; app: string };

/**
 * The full, SEO-rich article structure rendered on each platform tool page.
 * Stored as JSON in the `platform_content` table and generated by AI, with a
 * built-in fallback derived from the static `platform-content.ts` data.
 */
export type RichPlatformArticle = {
  answer: string;
  readingMinutes: number;
  lastUpdated: string;
  authorName: string;
  intro: string[];
  benefits: Benefit[];
  howToGeneral: Step[];
  androidSteps: string[];
  iphoneSteps: string[];
  pcSteps: string[];
  formats: string;
  useCases: string[];
  safety: string[];
  troubleshooting: string[];
  comparison: ComparisonRow[];
  alternatives: string;
  quickAnswers: QA[];
  faqs: QA[];
  keywords: string[];
};

const BRAND = "Free Online Video Downloader";

function estimateReadingMinutes(a: {
  intro: string[];
  formats: string;
  alternatives: string;
  benefits: Benefit[];
  faqs: QA[];
  quickAnswers: QA[];
  safety: string[];
  troubleshooting: string[];
}): number {
  const text = [
    ...a.intro,
    a.formats,
    a.alternatives,
    ...a.benefits.map((b) => `${b.title} ${b.text}`),
    ...a.faqs.map((f) => `${f.q} ${f.a}`),
    ...a.quickAnswers.map((f) => `${f.q} ${f.a}`),
    ...a.safety,
    ...a.troubleshooting,
  ].join(" ");
  const words = text.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(3, Math.round(words / 200));
}

/** Build a complete rich article from the static per-platform content. */
export function buildFallbackArticle(
  platform: Platform,
  base?: PlatformArticle,
): RichPlatformArticle {
  const article = base ?? getArticle(platform.slug);
  const name = platform.name;
  const audio = platform.audio;

  const answer =
    article?.answer ??
    `${BRAND} is a free online ${name} video downloader that saves ${name} videos${audio ? " and audio" : ""} in high quality — no app, login or watermark.`;

  const intro = article?.intro ?? [
    `${BRAND}'s ${name} downloader lets you save public ${name} videos straight to your phone, tablet or computer. Paste a link and download a clean file in seconds — completely free and with no sign-up.`,
    `Everything runs in your browser, so there is nothing to install and no account to create. It works the same on Android, iPhone, Windows and Mac.`,
  ];

  const benefits: Benefit[] =
    article?.features?.map((f) => ({ title: f.title, text: f.text })) ?? [
      { title: "Fast & free", text: `Download ${name} videos instantly with no limits or hidden fees.` },
      { title: "No app needed", text: "Works right in your browser — nothing to install." },
      { title: "Every device", text: "Use it on Android, iPhone, Windows and Mac." },
      { title: "No login", text: `Only a public ${name} link is required — your account stays private.` },
    ];

  const howToGeneral: Step[] = [
    { title: "Copy the link", text: `Copy the ${name} video URL from the app or your browser.` },
    { title: `Paste into ${BRAND}`, text: "Paste the link into the download box and press Download." },
    { title: "Choose quality & save", text: `Pick your resolution${audio ? " or MP3" : ""} and save the file to your device.` },
  ];

  const androidSteps = [
    `Open the ${name} video and tap Share or the menu, then Copy link.`,
    `Open ${BRAND} in Chrome and paste the link.`,
    "Tap Download — the file lands in your Downloads or Files folder.",
  ];
  const iphoneSteps = [
    `Open the ${name} video in Safari or the app and copy the link.`,
    `Open ${BRAND} and paste the link.`,
    "Tap Download — save it to Files or Photos.",
  ];
  const pcSteps = [
    `Open the ${name} video and copy its URL from the address bar or Share menu.`,
    `Open ${BRAND} in a new tab and paste the link.`,
    "Click Download — the file saves to your Downloads folder.",
  ];

  const formats =
    article?.formats ??
    `${name} downloads are delivered as MP4 for maximum device compatibility${audio ? ", with audio also available as MP3" : ""}. ${BRAND} always pulls the best quality the platform provides for the link you paste.`;

  const useCases = article?.useCases ?? [
    "Save videos for offline viewing on slow connections",
    "Keep your own posts as a personal backup",
    "Collect reference clips for editing and study",
    "Archive public content before it disappears",
  ];

  const safety = [
    `${BRAND} is safe to use — it never asks for a login, payment or app install.`,
    `Only download content you own, public content, or content you have permission to save. Downloading copyright-protected videos for anything beyond personal use may breach ${name}'s terms and local law.`,
    platform.slug === "youtube"
      ? "YouTube's Terms of Service only allow downloads where the creator has granted permission or the content is copyright-free — always check before saving."
      : `Respect creator rights and ${name}'s platform rules; DMCA-protected content cannot and should not be downloaded.`,
    "Some platforms use CAPTCHA or bot protection that can block downloads — if a video won't save, it may be due to those security settings.",
    "Private, restricted, deleted or login-only videos cannot be downloaded.",
  ];

  const troubleshooting = [
    "The video is private — only public videos can be downloaded.",
    "The link is incomplete — copy the full URL, not a truncated version.",
    `${name} changed its link format — try again shortly.`,
    "Your connection is slow — retry or pick a lower quality.",
    "Your browser is blocking it — turn off any ad-blocker for a moment.",
    "The video was deleted — removed content can't be downloaded.",
  ];

  const comparison: ComparisonRow[] = [
    { feature: "Installation", online: "None needed", app: "Required" },
    { feature: "Storage", online: "Uses no device storage", app: "Takes up space" },
    { feature: "Updates", online: "Automatic (browser-based)", app: "Manual" },
    { feature: "Mobile & PC", online: "Both, from the browser", app: "Separate apps" },
    { feature: "Privacy", online: "No login needed", app: "Often needs an account" },
    { feature: "Cost", online: "Free", app: "Often paid or ad-heavy" },
  ];

  const alternatives = `There are many online video downloaders available. Some support only a single platform, while all-in-one tools like ${BRAND} cover ${name} and many other platforms from one place, with no login and a clean interface. Whichever tool you choose, check that it is safe, ad-light and does not ask for unnecessary permissions or your account details.`;

  const faqs: QA[] = article?.faqs ?? [
    { q: `Is the ${name} downloader free?`, a: `Yes. Downloading ${name} videos with ${BRAND} is completely free with no limits or sign-up.` },
    { q: "Do I need to install an app?", a: `No. ${BRAND} runs entirely in your browser on any device.` },
    { q: `Can I download private ${name} videos?`, a: "No. Only public content can be downloaded; private or restricted posts are not accessible." },
  ];

  const quickAnswers: QA[] = faqs.slice(0, 6).map((f) => ({ q: f.q, a: f.a }));

  const keywords = article?.keywords ?? [
    `${platform.slug} video downloader`,
    `download ${platform.slug} videos`,
    `${platform.slug} downloader online`,
  ];

  const partial = {
    intro,
    formats,
    alternatives,
    benefits,
    faqs,
    quickAnswers,
    safety,
    troubleshooting,
  };

  return {
    answer,
    readingMinutes: estimateReadingMinutes(partial),
    lastUpdated: new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" }),
    authorName: "Editorial Team",
    intro,
    benefits,
    howToGeneral,
    androidSteps,
    iphoneSteps,
    pcSteps,
    formats,
    useCases,
    safety,
    troubleshooting,
    comparison,
    alternatives,
    quickAnswers,
    faqs,
    keywords,
  };
}

/** Merge stored JSON content over the fallback so partial content still renders. */
export function normalizeArticle(
  platform: Platform,
  stored: unknown,
): RichPlatformArticle {
  const fallback = buildFallbackArticle(platform);
  if (!stored || typeof stored !== "object") return fallback;
  const s = stored as Partial<RichPlatformArticle>;

  const arr = <T>(v: unknown, fb: T[]): T[] =>
    Array.isArray(v) && v.length ? (v as T[]) : fb;
  const str = (v: unknown, fb: string): string =>
    typeof v === "string" && v.trim() ? v : fb;

  const merged: RichPlatformArticle = {
    answer: str(s.answer, fallback.answer),
    readingMinutes:
      typeof s.readingMinutes === "number" && s.readingMinutes > 0
        ? s.readingMinutes
        : fallback.readingMinutes,
    lastUpdated: str(s.lastUpdated, fallback.lastUpdated),
    authorName: str(s.authorName, fallback.authorName),
    intro: arr(s.intro, fallback.intro),
    benefits: arr(s.benefits, fallback.benefits),
    howToGeneral: arr(s.howToGeneral, fallback.howToGeneral),
    androidSteps: arr(s.androidSteps, fallback.androidSteps),
    iphoneSteps: arr(s.iphoneSteps, fallback.iphoneSteps),
    pcSteps: arr(s.pcSteps, fallback.pcSteps),
    formats: str(s.formats, fallback.formats),
    useCases: arr(s.useCases, fallback.useCases),
    safety: arr(s.safety, fallback.safety),
    troubleshooting: arr(s.troubleshooting, fallback.troubleshooting),
    comparison: arr(s.comparison, fallback.comparison),
    alternatives: str(s.alternatives, fallback.alternatives),
    quickAnswers: arr(s.quickAnswers, fallback.quickAnswers),
    faqs: arr(s.faqs, fallback.faqs),
    keywords: arr(s.keywords, fallback.keywords),
  };
  return merged;
}
