/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowToDownloadRouteImport } from './routes/how-to-download'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PlatformRouteImport } from './routes/$platform'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiAiWriterChatRouteImport } from './routes/api/ai-writer-chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin.tools'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin.ads'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'
import { Route as AuthenticatedAdminToolsIndexRouteImport } from './routes/_authenticated/admin.tools.index'
import { Route as AuthenticatedAdminPagesIndexRouteImport } from './routes/_authenticated/admin.pages.index'
import { Route as ApiPublicHooksSeoAuditRouteImport } from './routes/api/public/hooks/seo-audit'
import { Route as AuthenticatedAdminToolsSlugRouteImport } from './routes/_authenticated/admin.tools.$slug'
import { Route as AuthenticatedAdminPagesKeyRouteImport } from './routes/_authenticated/admin.pages.$key'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToDownloadRoute = HowToDownloadRouteImport.update({
  id: '/how-to-download',
  path: '/how-to-download',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/$platform',
  path: '/$platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiWriterChatRoute = ApiAiWriterChatRouteImport.update({
  id: '/api/ai-writer-chat',
  path: '/api/ai-writer-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminToolsIndexRoute =
  AuthenticatedAdminToolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminToolsRoute,
  } as any)
const AuthenticatedAdminPagesIndexRoute =
  AuthenticatedAdminPagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPagesRoute,
  } as any)
const ApiPublicHooksSeoAuditRoute = ApiPublicHooksSeoAuditRouteImport.update({
  id: '/api/public/hooks/seo-audit',
  path: '/api/public/hooks/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminToolsSlugRoute =
  AuthenticatedAdminToolsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAdminToolsRoute,
  } as any)
const AuthenticatedAdminPagesKeyRoute =
  AuthenticatedAdminPagesKeyRouteImport.update({
    id: '/$key',
    path: '/$key',
    getParentRoute: () => AuthenticatedAdminPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$platform': typeof PlatformRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/how-to-download': typeof HowToDownloadRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/ai-writer-chat': typeof ApiAiWriterChatRoute
  '/api/download': typeof ApiDownloadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRouteWithChildren
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/pages/$key': typeof AuthenticatedAdminPagesKeyRoute
  '/admin/tools/$slug': typeof AuthenticatedAdminToolsSlugRoute
  '/api/public/hooks/seo-audit': typeof ApiPublicHooksSeoAuditRoute
  '/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/tools/': typeof AuthenticatedAdminToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$platform': typeof PlatformRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/how-to-download': typeof HowToDownloadRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/ai-writer-chat': typeof ApiAiWriterChatRoute
  '/api/download': typeof ApiDownloadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/pages/$key': typeof AuthenticatedAdminPagesKeyRoute
  '/admin/tools/$slug': typeof AuthenticatedAdminToolsSlugRoute
  '/api/public/hooks/seo-audit': typeof ApiPublicHooksSeoAuditRoute
  '/admin/pages': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/tools': typeof AuthenticatedAdminToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$platform': typeof PlatformRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/how-to-download': typeof HowToDownloadRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/ai-writer-chat': typeof ApiAiWriterChatRoute
  '/api/download': typeof ApiDownloadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRouteWithChildren
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/tools': typeof AuthenticatedAdminToolsRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/pages/$key': typeof AuthenticatedAdminPagesKeyRoute
  '/_authenticated/admin/tools/$slug': typeof AuthenticatedAdminToolsSlugRoute
  '/api/public/hooks/seo-audit': typeof ApiPublicHooksSeoAuditRoute
  '/_authenticated/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/_authenticated/admin/tools/': typeof AuthenticatedAdminToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$platform'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dmca'
    | '/faq'
    | '/how-to-download'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/api/ai-writer-chat'
    | '/api/download'
    | '/blog/$slug'
    | '/blog/'
    | '/admin/$id'
    | '/admin/ads'
    | '/admin/ai'
    | '/admin/new'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/tools'
    | '/admin/'
    | '/admin/pages/$key'
    | '/admin/tools/$slug'
    | '/api/public/hooks/seo-audit'
    | '/admin/pages/'
    | '/admin/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$platform'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dmca'
    | '/faq'
    | '/how-to-download'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/api/ai-writer-chat'
    | '/api/download'
    | '/blog/$slug'
    | '/blog'
    | '/admin/$id'
    | '/admin/ads'
    | '/admin/ai'
    | '/admin/new'
    | '/admin/seo'
    | '/admin'
    | '/admin/pages/$key'
    | '/admin/tools/$slug'
    | '/api/public/hooks/seo-audit'
    | '/admin/pages'
    | '/admin/tools'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$platform'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dmca'
    | '/faq'
    | '/how-to-download'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/api/ai-writer-chat'
    | '/api/download'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/tools'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/pages/$key'
    | '/_authenticated/admin/tools/$slug'
    | '/api/public/hooks/seo-audit'
    | '/_authenticated/admin/pages/'
    | '/_authenticated/admin/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PlatformRoute: typeof PlatformRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DmcaRoute: typeof DmcaRoute
  FaqRoute: typeof FaqRoute
  HowToDownloadRoute: typeof HowToDownloadRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiAiWriterChatRoute: typeof ApiAiWriterChatRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiPublicHooksSeoAuditRoute: typeof ApiPublicHooksSeoAuditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-download': {
      id: '/how-to-download'
      path: '/how-to-download'
      fullPath: '/how-to-download'
      preLoaderRoute: typeof HowToDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$platform': {
      id: '/$platform'
      path: '/$platform'
      fullPath: '/$platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-writer-chat': {
      id: '/api/ai-writer-chat'
      path: '/api/ai-writer-chat'
      fullPath: '/api/ai-writer-chat'
      preLoaderRoute: typeof ApiAiWriterChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tools': {
      id: '/_authenticated/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tools/': {
      id: '/_authenticated/admin/tools/'
      path: '/'
      fullPath: '/admin/tools/'
      preLoaderRoute: typeof AuthenticatedAdminToolsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminToolsRoute
    }
    '/_authenticated/admin/pages/': {
      id: '/_authenticated/admin/pages/'
      path: '/'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AuthenticatedAdminPagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPagesRoute
    }
    '/api/public/hooks/seo-audit': {
      id: '/api/public/hooks/seo-audit'
      path: '/api/public/hooks/seo-audit'
      fullPath: '/api/public/hooks/seo-audit'
      preLoaderRoute: typeof ApiPublicHooksSeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/tools/$slug': {
      id: '/_authenticated/admin/tools/$slug'
      path: '/$slug'
      fullPath: '/admin/tools/$slug'
      preLoaderRoute: typeof AuthenticatedAdminToolsSlugRouteImport
      parentRoute: typeof AuthenticatedAdminToolsRoute
    }
    '/_authenticated/admin/pages/$key': {
      id: '/_authenticated/admin/pages/$key'
      path: '/$key'
      fullPath: '/admin/pages/$key'
      preLoaderRoute: typeof AuthenticatedAdminPagesKeyRouteImport
      parentRoute: typeof AuthenticatedAdminPagesRoute
    }
  }
}

interface AuthenticatedAdminPagesRouteChildren {
  AuthenticatedAdminPagesKeyRoute: typeof AuthenticatedAdminPagesKeyRoute
  AuthenticatedAdminPagesIndexRoute: typeof AuthenticatedAdminPagesIndexRoute
}

const AuthenticatedAdminPagesRouteChildren: AuthenticatedAdminPagesRouteChildren =
  {
    AuthenticatedAdminPagesKeyRoute: AuthenticatedAdminPagesKeyRoute,
    AuthenticatedAdminPagesIndexRoute: AuthenticatedAdminPagesIndexRoute,
  }

const AuthenticatedAdminPagesRouteWithChildren =
  AuthenticatedAdminPagesRoute._addFileChildren(
    AuthenticatedAdminPagesRouteChildren,
  )

interface AuthenticatedAdminToolsRouteChildren {
  AuthenticatedAdminToolsSlugRoute: typeof AuthenticatedAdminToolsSlugRoute
  AuthenticatedAdminToolsIndexRoute: typeof AuthenticatedAdminToolsIndexRoute
}

const AuthenticatedAdminToolsRouteChildren: AuthenticatedAdminToolsRouteChildren =
  {
    AuthenticatedAdminToolsSlugRoute: AuthenticatedAdminToolsSlugRoute,
    AuthenticatedAdminToolsIndexRoute: AuthenticatedAdminToolsIndexRoute,
  }

const AuthenticatedAdminToolsRouteWithChildren =
  AuthenticatedAdminToolsRoute._addFileChildren(
    AuthenticatedAdminToolsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRouteWithChildren
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRouteWithChildren,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PlatformRoute: PlatformRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DmcaRoute: DmcaRoute,
  FaqRoute: FaqRoute,
  HowToDownloadRoute: HowToDownloadRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiAiWriterChatRoute: ApiAiWriterChatRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiPublicHooksSeoAuditRoute: ApiPublicHooksSeoAuditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
